apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yetibot.fullname" . }}
  labels:
    {{- include "yetibot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "yetibot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # roll new pods when config changes
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
      {{- with .Values.deployment.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "yetibot.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "yetibot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # pull in every KV from the configmap to use as environment
          envFrom:
          - configMapRef:
              name: {{ include "yetibot.fullname" . }}
          - secretRef:
              name: {{ include "yetibot.fullname" . }}
          ports:
            - name: http
              containerPort: 3003
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            failureThreshold: 3
            periodSeconds: 30
            initialDelaySeconds: 60
          # requires K8S 1.16+
          # startupProbe:
          #   httpGet:
          #     path: /healthz
          #     port: liveness-port
          #   failureThreshold: 30
          #   periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
