apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yetibot.fullname" . }}
  labels:
    {{- include "yetibot.labels" . | nindent 4 }}
type: Opaque
data:
  # fill in with your configuration values. these will show up as env vars in
  # the pod. see:
  # https://github.com/yetibot/yetibot.core/blob/master/config/sample.env
  # for the full list.
