apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yetibot.fullname" . }}
  labels:
    {{- include "yetibot.labels" . | nindent 4 }}
data:
  # Sample Yetibot config. Populate these values (at minimum configure an
  # adapter) with your own config or secrets.
  {{- range $key, $value := .Values.yetibot.env }}
    {{ $key }}: "{{ $value }}"
  {{- end }}
