apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  # Sample Yetibot config. Populate these values (at minimum configure an
  # adapter) with your own secrets.
  yetibot.edn: |
    {{.Values.yetibot.edn | indent 4 }}
