name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # Note: this will fail unless app version was bumped
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@1.0.0
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
