name: Release Charts

on:
  push:
    branches:
      - master
    paths:
      - charts/yetibot/Chart.yaml

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # must fetch all history so that CR can compare latest tag to current
        # commit. otherwise it will skip releasing, e.g.:
        # > Looking up latest tag...
        # > Discovering changed charts since '5018edb0c13cd99925cbfc417f78433eb3fc26af'...
        # > Nothing to do. No chart changes detected.
        # from https://github.com/yetibot/yetibot-helm/runs/1353828038
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # Note: this will fail unless app version was bumped
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
