
name: Handle repository dispatch events

# this allows other repos to send a release dispatch here which then triggers a
# version bump
on:
  repository_dispatch:
    types: [bump]

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: debug
        run: |
          sed -i "s/^appVersion.*$/appVersion: ${{ github.event.client_payload.message.yb_version }}/" charts/yetibot/Chart.yaml
          # auto bump patch version:
          sed -i "s/^(version: )([0-9]+)\.([0-9]+)\.([0-9]+)/echo version: \2.\3.$((\4+1))/ge" charts/yetibot/Chart.yaml
          git diff
